# ProbSet1
Bethany Bailey

### Intro to Numpy

### Problem 1

In [1]:
import numpy as np

In [21]:
def Problem1():
    A = np.array( [ [3, -1, 4],[1, 5, -9] ] )
    B = np.array( [ [2, 6, -5, 3],[5, -8, 9, 7],[9, -3, -2, -3] ] )
    return A @ B

In [66]:
print("The matrix product is \n", Problem1())

The matrix product is 
 [[ 37  14 -32 -10]
 [-54  -7  58  65]]


### Problem 2

In [67]:
def Problem2():
    A = np.array( [[3,1,4],[1,5,9],[-5,3,1]] )
    return (- (A @ A @ A) + 9 * (A @ A) - 15 * A)

In [68]:
print("The answer to problem 2 is \n", Problem2())

The answer to problem 2 is 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


### Problem 3

In [69]:
def Problem3():
    ones = np.ones((7,7))
    A = np.triu(ones)
    fives = ones * 5
    negones = ones * -1
    B1 = np.triu(fives, 1)
    B2 = np.tril(negones)
    B = B1 + B2
    A = A.astype(np.int64)
    B = B.astype(np.int64)
    return A @ B @ A

In [70]:
print("The answer to problem 3 is \n", Problem3())

The answer to problem 3 is 
 [[ -7  -8  -3   8  25  48  77]
 [ -6 -12 -12  -6   6  24  48]
 [ -5 -10 -15 -14  -7   6  25]
 [ -4  -8 -12 -16 -14  -6   8]
 [ -3  -6  -9 -12 -15 -12  -3]
 [ -2  -4  -6  -8 -10 -12  -8]
 [ -1  -2  -3  -4  -5  -6  -7]]


### Problem 4

In [75]:
def Problem4(array):
    cp = np.copy(array)
    mask = cp < 0
    cp[mask] = 0
    return cp

In [76]:
array = np.array( [ [1,2,3], [-1, -2, 0], [1, 0, -100] ] )
print("An example of the output to problem 4 with array \n", array, "is \n", Problem4(array))

An example of the output to problem 4 with array 
 [[   1    2    3]
 [  -1   -2    0]
 [   1    0 -100]] is 
 [[1 2 3]
 [0 0 0]
 [1 0 0]]


### Problem 5

In [100]:
def Problem5():
    A = np.array( [ [0, 2, 4], [1, 3, 5] ])
    B = np.array( [ [3, 0, 0], [3, 3, 0], [3, 3, 3]])
    C = np.diag([-2, -2, -2])
    block1 = np.vstack((np.zeros((3,3)), A, B))
    block2 = np.vstack((A.T, np.zeros((2,2)), np.zeros((3,2))))
    block3 = np.vstack((np.eye((3)), np.zeros((2,3)), C))
    return np.hstack((block1, block2, block3))

In [102]:
print("The answer to problem 5 is \n", Problem5())

The answer to problem 5 is 
 [[ 0.  0.  0.  0.  1.  1.  0.  0.]
 [ 0.  0.  0.  2.  3.  0.  1.  0.]
 [ 0.  0.  0.  4.  5.  0.  0.  1.]
 [ 0.  2.  4.  0.  0.  0.  0.  0.]
 [ 1.  3.  5.  0.  0.  0.  0.  0.]
 [ 3.  0.  0.  0.  0. -2.  0.  0.]
 [ 3.  3.  0.  0.  0.  0. -2.  0.]
 [ 3.  3.  3.  0.  0.  0.  0. -2.]]


### Problem 6

In [165]:
def Problem6(array):
    sums = array.sum(axis=1).reshape((array.shape[0], 1))
    rv = array / sums
    return rv

In [168]:
array = np.array( [ [1,3],[1,1] ] )
print("The answer to problem 6 is \n", Problem6(array))

The answer to problem 6 is 
 [[ 0.25  0.75]
 [ 0.5   0.5 ]]


### Problem 7

In [302]:
def Problem7(array, operation):
    if operation == "right_diag":
        rv = np.max(array[:17, :17] * array[1:18, 1:18] * array[2:19, 2:19] * array[3:20, 3:20])
    if operation == "left_diag":
        rv = np.max(array[:-3, 3:] * array[1:-2, 2:-1] * array[2:-1, 1:-2] * array[3:, :-3])
    if operation == "horizontal":
        rv = np.max(array[:, :-3] * array[:, 1:-2] * array[:, 2:-1] * array[:, 3:])
    if operation == "vertical":
        rv = np.max(array[:-3, :] * array[1:-2, :] * array[2:-1, :] * array[3:, :])
    return rv

In [303]:
grid = np.load("grid.npy")

In [304]:
print("The answer to problem 7 for the right diagonal is", Problem7(grid, operation = "right_diag"))
print("The answer to problem 7 for the left diagonal is", Problem7(grid, operation = "left_diag"))
print("The answer to problem 7 for the horizontal is", Problem7(grid, operation = "horizontal"))
print("The answer to problem 7 for the vertical is", Problem7(grid, operation = "vertical"))

The answer to problem 7 for the right diagonal is 40304286
The answer to problem 7 for the left diagonal is 70600674
The answer to problem 7 for the horizontal is 48477312
The answer to problem 7 for the vertical is 51267216


## The Standard Library

### Problem 1

In [280]:
def Problem1(L):
    return (min(L), max(L), sum(L)/len(L))

In [281]:
L = [1, 2, 3, 4]
answer = Problem1(L)
print("The answer for problem 1 for list", L, "is min =", answer[0], ", max =", answer[1], ", avg =", answer[2])

The answer for problem 1 for list [1, 2, 3, 4] is min = 1 , max = 4 , avg = 2.5


### Problem 2

In [288]:
def Problem2():
    an_int = 1
    an_int1 = an_int
    an_int1 += 1
    print("Ints are immutable:", an_int1 == an_int)
    a_str = "the"
    a_str1 = a_str
    a_str1 += " red"
    print("Strs are immutable:", a_str1 == a_str)
    a_list = [1, 1]
    a_list1 = a_list
    a_list1 += [2, 2]
    print("Lists are immutable:", a_list1 == a_list)
    a_tuple = (1, 1)
    a_tuple1 = a_tuple
    a_tuple1 += (1,)
    print("Tuples are immutable:", a_tuple1 == a_tuple)
    a_set = {1, 1}
    a_set1 = a_set
    a_set1.add(2)
    print("Sets are immutable:", a_set1 == a_set)

In [289]:
Problem2()

Ints are immutable: False
Strs are immutable: False
Lists are immutable: True
Tuples are immutable: False
Sets are immutable: True


### Problem 3

In [297]:
%run calculator.py

In [307]:
def hypotenuse(l, w):
    rv = sqrt(calc_sum(calc_product(l, l), calc_product(w, w)))
    return rv

In [309]:
print("Length of hypotenuse of right triangle with length 2, width 2 is", hypotenuse(2, 2))

Length of hypotenuse of right triangle with length 2, width 2 is 2.8284271247461903


### Problem 4

In [ ]:
def Problem4(i):
    