# ProbSet1
Bethany Bailey

### Intro to Numpy

### Problem 1

In [2]:
import numpy as np

In [3]:
def Problem1():
    A = np.array( [ [3, -1, 4],[1, 5, -9] ] )
    B = np.array( [ [2, 6, -5, 3],[5, -8, 9, 7],[9, -3, -2, -3] ] )
    return A @ B

In [4]:
print("The matrix product is \n", Problem1())

The matrix product is 
 [[ 37  14 -32 -10]
 [-54  -7  58  65]]


### Problem 2

In [5]:
def Problem2():
    A = np.array( [[3,1,4],[1,5,9],[-5,3,1]] )
    return (- (A @ A @ A) + 9 * (A @ A) - 15 * A)

In [6]:
print("The answer to problem 2 is \n", Problem2())

The answer to problem 2 is 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


### Problem 3

In [7]:
def Problem3():
    ones = np.ones((7,7))
    A = np.triu(ones)
    fives = ones * 5
    negones = ones * -1
    B1 = np.triu(fives, 1)
    B2 = np.tril(negones)
    B = B1 + B2
    A = A.astype(np.int64)
    B = B.astype(np.int64)
    return A @ B @ A

In [8]:
print("The answer to problem 3 is \n", Problem3())

The answer to problem 3 is 
 [[ -7  -8  -3   8  25  48  77]
 [ -6 -12 -12  -6   6  24  48]
 [ -5 -10 -15 -14  -7   6  25]
 [ -4  -8 -12 -16 -14  -6   8]
 [ -3  -6  -9 -12 -15 -12  -3]
 [ -2  -4  -6  -8 -10 -12  -8]
 [ -1  -2  -3  -4  -5  -6  -7]]


### Problem 4

In [14]:
def Problem4(array):
    cp = np.copy(array)
    mask = array < 0
    cp[mask] = 0
    return cp

In [15]:
array = np.array( [ [1,2,3], [-1, -2, 0], [1, 0, -100] ] )
print("An example of the output to problem 4 with array \n", array, "is \n", Problem4(array))

An example of the output to problem 4 with array 
 [[   1    2    3]
 [  -1   -2    0]
 [   1    0 -100]] is 
 [[1 2 3]
 [0 0 0]
 [1 0 0]]


### Problem 5

In [16]:
def Problem5():
    A = np.array( [ [0, 2, 4], [1, 3, 5] ])
    B = np.array( [ [3, 0, 0], [3, 3, 0], [3, 3, 3]])
    C = np.diag([-2, -2, -2])
    block1 = np.vstack((np.zeros((3,3)), A, B))
    block2 = np.vstack((A.T, np.zeros((2,2)), np.zeros((3,2))))
    block3 = np.vstack((np.eye((3)), np.zeros((2,3)), C))
    return np.hstack((block1, block2, block3))

In [17]:
print("The answer to problem 5 is \n", Problem5())

The answer to problem 5 is 
 [[ 0.  0.  0.  0.  1.  1.  0.  0.]
 [ 0.  0.  0.  2.  3.  0.  1.  0.]
 [ 0.  0.  0.  4.  5.  0.  0.  1.]
 [ 0.  2.  4.  0.  0.  0.  0.  0.]
 [ 1.  3.  5.  0.  0.  0.  0.  0.]
 [ 3.  0.  0.  0.  0. -2.  0.  0.]
 [ 3.  3.  0.  0.  0.  0. -2.  0.]
 [ 3.  3.  3.  0.  0.  0.  0. -2.]]


### Problem 6

In [18]:
def Problem6(array):
    sums = array.sum(axis=1).reshape((array.shape[0], 1))
    rv = array / sums
    return rv

In [19]:
array = np.array( [ [1,3],[1,1] ] )
print("The answer to problem 6 is \n", Problem6(array))

The answer to problem 6 is 
 [[ 0.25  0.75]
 [ 0.5   0.5 ]]


### Problem 7

In [20]:
def Problem7(array, operation):
    if operation == "right_diag":
        rv = np.max(array[:17, :17] * array[1:18, 1:18] * array[2:19, 2:19] * array[3:20, 3:20])
    if operation == "left_diag":
        rv = np.max(array[:-3, 3:] * array[1:-2, 2:-1] * array[2:-1, 1:-2] * array[3:, :-3])
    if operation == "horizontal":
        rv = np.max(array[:, :-3] * array[:, 1:-2] * array[:, 2:-1] * array[:, 3:])
    if operation == "vertical":
        rv = np.max(array[:-3, :] * array[1:-2, :] * array[2:-1, :] * array[3:, :])
    return rv

In [21]:
grid = np.load("grid.npy")

In [22]:
print("The answer to problem 7 for the right diagonal is", Problem7(grid, operation = "right_diag"))
print("The answer to problem 7 for the left diagonal is", Problem7(grid, operation = "left_diag"))
print("The answer to problem 7 for the horizontal is", Problem7(grid, operation = "horizontal"))
print("The answer to problem 7 for the vertical is", Problem7(grid, operation = "vertical"))

The answer to problem 7 for the right diagonal is 40304286
The answer to problem 7 for the left diagonal is 70600674
The answer to problem 7 for the horizontal is 48477312
The answer to problem 7 for the vertical is 51267216


## The Standard Library

### Problem 1

In [23]:
def Problem1(L):
    return (min(L), max(L), sum(L)/len(L))

In [24]:
L = [1, 2, 3, 4]
answer = Problem1(L)
print("The answer for problem 1 for list", L, "is min =", answer[0], ", max =", answer[1], ", avg =", answer[2])

The answer for problem 1 for list [1, 2, 3, 4] is min = 1 , max = 4 , avg = 2.5


### Problem 2

In [25]:
def Problem2():
    an_int = 1
    an_int1 = an_int
    an_int1 += 1
    print("Ints are immutable:", an_int1 == an_int)
    a_str = "the"
    a_str1 = a_str
    a_str1 += " red"
    print("Strs are immutable:", a_str1 == a_str)
    a_list = [1, 1]
    a_list1 = a_list
    a_list1 += [2, 2]
    print("Lists are immutable:", a_list1 == a_list)
    a_tuple = (1, 1)
    a_tuple1 = a_tuple
    a_tuple1 += (1,)
    print("Tuples are immutable:", a_tuple1 == a_tuple)
    a_set = {1, 1}
    a_set1 = a_set
    a_set1.add(2)
    print("Sets are immutable:", a_set1 == a_set)

In [26]:
Problem2()

Ints are immutable: False
Strs are immutable: False
Lists are immutable: True
Tuples are immutable: False
Sets are immutable: True


### Problem 3

In [27]:
%run calculator.py

In [28]:
def hypotenuse(l, w):
    rv = sqrt(calc_sum(calc_product(l, l), calc_product(w, w)))
    return rv

In [29]:
print("Length of hypotenuse of right triangle with length 2, width 2 is", hypotenuse(2, 2))

Length of hypotenuse of right triangle with length 2, width 2 is 2.8284271247461903


### Problem 4

In [74]:
from itertools import combinations

def Problem4(i):
    rv = [x for l in range(len(i)+1) for x in combinations(i, l)]
    return rv

In [75]:
Problem4("ABC")

[(),
 ('A',),
 ('B',),
 ('C',),
 ('A', 'B'),
 ('A', 'C'),
 ('B', 'C'),
 ('A', 'B', 'C')]

### Problem 5

Please see shutthebox.py and updates to box.py and run the following command on the command line:

$ python shutthebox.py "Beth" 60.0

## Unit Testing
### See solutions.py and test_solutions.py for answers.

## Object-Oriented Programming
### Problem 1

In [14]:
class Backpack:
    """A Backpack object class. Has a name, color, maximum size, and a list of contents.
    Attributes:
        name (str): the name of the backpack's owner.
        color (str): the color of the backpack.
        max_size (int): the maximum amount of items in the backpack.
        contents (list): the contents of the backpack.
    Functions:
        put(): Add an item to the backpack.
        take(): Remove and item from the backpack.
        dump(): Remove all the contents from the backpack.
    """
    
    def __init__(self, name, color, max_size=5):           # This function is the constructor.
        """Set the name, color, and max_size and initialize an empty list of contents.
        Parameters:
            name (str): the name of the backpack's owner.
            color (str): the color of the backpack.
            max_size (int): the maximum amount of items in the backpack.
        """
        self.name = name
        self.color = color
        self.max_size = max_size
        self.contents = []
    
    def put(self, item):
        """Check if there is room in the backpack. If there is,
        add 'item' to the backpack's list of contents. Else, tell the user that there is no room."""
        if len(self.contents) >= self.max_size:
            print("No Room!")
            return
        else:
            self.contents.append(item)  # Use 'self.contents', not just 'contents'.
        
    def take(self, item):
        """Remove 'item' from the backpack's list of contents."""
        self.contents.remove(item)
        
    def dump(self):
        """Dump all of the contents from the backpack."""
        self.contents = []

In [15]:
def test_backpack():
    testpack = Backpack("Barry", "black")       # Instantiate the object.
    if testpack.name != "Barry":                # Test an attribute.
        print("Backpack.name assigned incorrectly")
    for item in ["pencil", "pen", "paper", "computer"]:
        testpack.put(item)                      # Test a method.
    print("Contents:", testpack.contents)
    testpack.take("pencil")
    print("Contents:", testpack.contents)
    testpack.dump()
    print("Contents:", testpack.contents)

In [16]:
test_backpack()

Contents: ['pencil', 'pen', 'paper', 'computer']
Contents: ['pen', 'paper', 'computer']
Contents: []


### Problem 2

In [19]:
# Inherit from the Backpack class in the class definition.
class Jetpack(Backpack):
    """A Jetpack object class. Inherits from the Backpack class.
    A jetpack is a fueled backpack.
    Attributes:
        name (str): the name of the jetpack's owner.
        color (str): the color of the jetpack.
        max_size (int): the maximum amount of fuel that can fit inside.
        fuel_amount (int): how much fuel the with which the jetpack starts.
"""
    def __init__(self, name, color, max_size=2, fuel_amount=10):
        """Use the Backpack constructor to initialize the name, color,
        and max_size attributes. A knapsack only holds 3 item by default.
        Parameters:
            name (str): the name of the jetpack's owner.
            color (str): the color of the jetpack.
            max_size (int): the maximum amount of fuel that can fit inside.
            fuel_amount (int): how much fuel the with which the jetpack starts.
"""
        Backpack.__init__(self, name, color, max_size)
        self.fuel_amount = fuel_amount
        
    def put(self, item):
        """Check if there is room in the backpack. If there is,
        add 'item' to the backpack's list of contents. Else, tell the user that there is no room."""
        if len(self.contents) >= self.max_size:
            print("No Room!")
            return
        else:
            self.contents.append(item)  # Use 'self.contents', not just 'contents'.
        
    def take(self, item):
        """Remove 'item' from the backpack's list of contents."""
        self.contents.remove(item)
        
    def fly(self, fuel_burned):
        """Check if there is enough fuel to burn. If so, burn the fuel. 
        Otherwise, let the user know there is not enough fuel."""
        if fuel_burned > self.fuel_amount:
            print("Not enough fuel!")
            return
        else:
            self.fuel_amount = fuel_burned
            
    def dump(self):
        """Dump all of the contents and fuel from the backpack."""
        self.fuel_amount = []
        self.contents = [] 

### Problem 3

In [41]:
class Backpack:
    """A Backpack object class. Has a name, color, maximum size, and a list of contents.
    Attributes:
        name (str): the name of the backpack's owner.
        color (str): the color of the backpack.
        max_size (int): the maximum amount of items in the backpack.
        contents (list): the contents of the backpack.
    Functions:
        put(): Add an item to the backpack.
        take(): Remove and item from the backpack.
        dump(): Remove all the contents from the backpack.
    """
    
    def __init__(self, name, color, max_size=5):           # This function is the constructor.
        """Set the name, color, and max_size and initialize an empty list of contents.
        Parameters:
            name (str): the name of the backpack's owner.
            color (str): the color of the backpack.
            max_size (int): the maximum amount of items in the backpack.
        """
        self.name = name
        self.color = color
        self.max_size = max_size
        self.contents = []
    
    def put(self, item):
        """Check if there is room in the backpack. If there is,
        add 'item' to the backpack's list of contents. Else, tell the user that there is no room."""
        if len(self.contents) >= self.max_size:
            print("No Room!")
            return
        else:
            self.contents.append(item)  # Use 'self.contents', not just 'contents'.
        
    def take(self, item):
        """Remove 'item' from the backpack's list of contents."""
        self.contents.remove(item)
        
    def dump(self):
        """Dump all of the contents from the backpack."""
        self.contents = []
        
    def __add__(self, other):
        """Add the number of contents of each Backpack."""
        return len(self.contents) + len(other.contents)
    
    def __lt__(self, other):
        """If 'self' has fewer contents than 'other', return True.
        Otherwise, return False.
        """
        return len(self.contents) < len(other.contents)

    def __eq__(self, other):
        """If 'self' is the same as 'other', return True.
        Otherwise, return False.
        """
        return self.name == other.name and self.color == other.color and len(self.contents) == \
            len(other.contents)
    
    def __str__(self):
        """Construct a return a string representation for this backpack."""
        return "Owner:\t\t{} \nColor:\t\t{} \nSize:\t\t{} \nMax Size:\t{} \
            \nContents:\t{}".format(self.name, self.color, len(self.contents), self.max_size, self.contents)

In [42]:
pack1 = Backpack("Rose", "red")
pack2 = Backpack("Rose", "red")

In [43]:
pack1 == pack2

True

In [44]:
print(pack1)

Owner:		Rose 
Color:		red 
Size:		0 
Max Size:	5             
Contents:	[]


### Problem 4

In [78]:
class ComplexNumber:
    
    def __init__(self, real, imag):
        self.real = real
        self.imag = imag
        
    def conjugate(self):
        conj = ComplexNumber(self.real, -self.imag)
        return conj
    
    def __str__(self):
        if self.imag >= 0:
            s = "({}+{}j)".format(self.real, self.imag)
        else:
            s = "({}{}j)".format(self.real, self.imag)
        return s
            
    def __abs__(self):
        return (self.real**2 + self.imag ** 2) ** .5
    
    def __eq__(self, other):
        return self.real == other.real and self.imag == other.imag
    
    def __add__(self, other):
        new_real = self.real + other.real
        new_imag = self.imag + other.imag
        return ComplexNumber(new_real, new_imag)
        
    def __sub__(self, other):
        new_real = self.real - other.real
        new_imag = self.imag - other.imag
        return ComplexNumber(new_real, new_imag)
    
    def __mul__(self, other):
        new_real = self.real * other.real - self.imag * other.imag
        new_imag = self.real * other.imag + self.imag * other.real
        return ComplexNumber(new_real, new_imag)
        
    def __truediv__(self, other):
        t = self*other.conjugate()
        b = (other*other.conjugate()).real
        return ComplexNumber(t.real / b, t.imag/b)

In [79]:
def test_ComplexNumber(a, b):
    py_cnum, my_cnum = complex(a, b), ComplexNumber(a, b)
    # Validate the constructor.
    if my_cnum.real != a or my_cnum.imag != b:
        print("__init__() set self.real and self.imag incorrectly")
    # Validate conjugate() by checking the new number's imag attribute.
    if py_cnum.conjugate().imag != my_cnum.conjugate().imag:
        print("conjugate() failed for", py_cnum)
    # Validate __str__().
    if str(py_cnum) != str(my_cnum):
        print("__str__() failed for", py_cnum)
    if abs(py_cnum) != abs(my_cnum):
        print("__abs__() failed for", py_cnum)
    if my_cnum != my_cnum:
        print("__eq__() failed for", py_cnum)    
    if py_cnum + py_cnum != my_cnum + my_cnum:
        print("__add__() failed for", py_cnum)
    if py_cnum - py_cnum != my_cnum - my_cnum:
        print("__sub__() failed for", py_cnum)
    if py_cnum * py_cnum != my_cnum * my_cnum:
        print("__mul__() failed for", py_cnum)    
    if py_cnum / py_cnum != my_cnum / my_cnum:
        print("__truediv__() failed for", py_cnum)

In [81]:
test_ComplexNumber(3, -4)
test_ComplexNumber(2, 5)

## Exceptions and File Input/Output

### Problem 1

The final number will always be 1089 because

In [51]:
def arithmagic():
    step_1 = input("Enter a 3-digit number where the first and last "
                                           "digits differ by 2 or more: ")
    if len(step_1) != 3:
        raise ValueError("The first number is not a 3-digit number.")
    if abs(int(step_1[0]) - int(step_1[2])) < 2:
        raise ValueError("The first number’s first and last digits differ by less than 2.")
    step_2 = input("Enter the reverse of the first number, obtained "
                                              "by reading it backwards: ")
    if step_1[::-1] != step_2:
        raise ValueError("The second number is not the reverse of the first number.")
    step_3 = input("Enter the positive difference of these numbers: ")
    if step_3 != str(abs(int(step_1) - int(step_2))):
        raise ValueError("The third number is not the positive difference of the first two numbers.")
    step_4 = input("Enter the reverse of the previous result: ")
    if step_3[::-1] != step_4:
        raise ValueError("The fourth number is not the reverse of the third number.")
    print(str(step_3), "+", str(step_4), "= 1089 (ta-da!)")

In [52]:
arithmagic()

Enter a 3-digit number where the first and last digits differ by 2 or more: 103
Enter the reverse of the first number, obtained by reading it backwards: 301
Enter the positive difference of these numbers: 198
Enter the reverse of the previous result: 891
198 + 891 = 1089 (ta-da!)


### Problem 2

In [68]:
from random import choice

def random_walk(max_iters=1e12):
    walk = 0
    directions = [1, -1]
    try:
        for i in range(int(max_iters)):
            walk += choice(directions)
    except KeyboardInterrupt:
        print("Process interrupted at iteration", i)
    else:
        print("Process completed.")
    finally:
        return walk

In [69]:
random_walk()

Process interrupted at iteration 2860746435


-38709

### Problem 3 & Problem 4

In [364]:
class ContentFilter():
    
    def __init__(self, filename):
        self.filename = filename
        trying = True
        while trying:
            try:
                file = open(self.filename, 'r')
                contents = file.readlines()
                self.num_lines = len(contents)
                trying = False
            except (FileNotFoundError, TypeError, OSError) as e:
                valid_name = input("Please enter a valid file name: ")
                self.filename = valid_name
        file.close()
        self.contents = ' '.join(contents)
        self.letters = 0
        self.digits = 0
        self.whitespace = 0
        for i in contents:
            for j in i:
                if j.isspace():
                    self.whitespace += 1
                if j.isdigit():
                    self.digits += 1
                if j.isalpha():
                    self.letters += 1
        
    def uniform(self, name, mode, case="upper"):
        if mode not in {'w', 'x', 'a'}:
            raise ValueError("Mode must be 'w', 'x', or 'a'.")
        if case == "upper":
            content = self.contents.upper()
        elif case == "lower":
            content = self.contents.lower()
        else:
            raise ValueError("Case not upper or lower.")
        with open(name, mode) as file:
            file.write(content)
            
    def reverse(self, name, mode, unit="line"):
        if mode not in {'w', 'x', 'a'}:
            raise ValueError("Mode must be 'w', 'x', or 'a'.")
        with open(name, mode) as file:
            if unit == "word":
                for i in self.contents.split("\n"):
                    for j in i.split(" ")[::-1]:
                        file.write(j + " ")
                    file.write("\n")
            elif unit == "line":
                for i in self.contents.split("\n")[::-1]:
                    file.write(i + "\n")
            else:
                raise ValueError("Unit not line or word.")
            
    def transpose(self, name, mode):
        if mode not in {'w', 'x', 'a'}:
            raise ValueError("Mode must be 'w', 'x', or 'a'.")
        with open(name, mode) as file:
            lines_content = self.contents.split("\n")
            lines = len(lines_content)
            words = len(lines_content[0].split(" "))
            for i in range(words):
                for j in range(lines):
                    words_content = lines_content[j].split(" ")
                    file.write(words_content[i])
                    file.write(" ")
                file.write("\n")
                
    def __str__(self):
        s = "Source file:\t{}\nTotal characters:\t{}\nAlphabetic characters:\t{}\nNumerical\
            characters:\t{}\nWhitespace characters:\t{}\nNumber of lines:\t{}".format(self.filename,\
            len(self.contents), self.letters, self.digits, self.whitespace, self.num_lines)
        return s

In [365]:
t = ContentFilter("testfile.txt")

In [366]:
t.contents

'This is a test file.\n \n It has 1 number.\n \n It has multiple lines of code.\n \n This is the end of the test file.'

In [367]:
print(t)

Source file:	testfile.txt
Total characters:	111
Alphabetic characters:	75
Numerical            characters:	1
Whitespace characters:	25
Number of lines:	7


In [368]:
cf = ContentFilter("cf_example1.txt")

In [369]:
cf.uniform("uniform.txt", mode='w', case="upper")
cf.uniform("uniform.txt", mode='a', case="lower")
cf.reverse("reverse.txt", mode='w', unit="word")
cf.reverse("reverse.txt", mode='a', unit="line")
cf.transpose("transpose.txt", mode='w')